use `B::Keywords` to spot more errors when running `mimedefang.pl -test` fix #33

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4482,6 +4482,61 @@ printf %s "checking for Perl module Mail::DKIM... " >&6; }
     { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $HAVE_DKIM" >&5
 printf "%s\n" "$HAVE_DKIM" >&6; }
 
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for Perl module Mail::BIMI >= 3" >&5
+printf %s "checking for Perl module Mail::BIMI >= 3... " >&6; }
+    (echo "use Mail::BIMI 3;" ; echo "exit(0);") | $PERL > /dev/null 2>&1
+    if test $? != 0 ; then
+	HAVE_BIMI=no
+    else
+	HAVE_BIMI=yes
+    fi
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $HAVE_BIMI" >&5
+printf "%s\n" "$HAVE_BIMI" >&6; }
+
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for Perl module Crypt::OpenSSL::X509" >&5
+printf %s "checking for Perl module Crypt::OpenSSL::X509... " >&6; }
+    (echo "use Crypt::OpenSSL::X509;" ; echo "exit(0);") | $PERL > /dev/null 2>&1
+    if test $? != 0 ; then
+	HAVE_CRYPT_OPENSSL_X509=no
+    else
+	HAVE_CRYPT_OPENSSL_X509=yes
+    fi
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $HAVE_CRYPT_OPENSSL_X509" >&5
+printf "%s\n" "$HAVE_CRYPT_OPENSSL_X509" >&6; }
+
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for Perl module AnyEvent" >&5
+printf %s "checking for Perl module AnyEvent... " >&6; }
+    (echo "use AnyEvent;" ; echo "exit(0);") | $PERL > /dev/null 2>&1
+    if test $? != 0 ; then
+	HAVE_ANYEVENT=no
+    else
+	HAVE_ANYEVENT=yes
+    fi
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $HAVE_ANYEVENT" >&5
+printf "%s\n" "$HAVE_ANYEVENT" >&6; }
+
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for Perl module AnyEvent::DNS" >&5
+printf %s "checking for Perl module AnyEvent::DNS... " >&6; }
+    (echo "use AnyEvent::DNS;" ; echo "exit(0);") | $PERL > /dev/null 2>&1
+    if test $? != 0 ; then
+	HAVE_ANYEVENT_DNS=no
+    else
+	HAVE_ANYEVENT_DNS=yes
+    fi
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $HAVE_ANYEVENT_DNS" >&5
+printf "%s\n" "$HAVE_ANYEVENT_DNS" >&6; }
+
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for Perl module AnyEvent::Socket" >&5
+printf %s "checking for Perl module AnyEvent::Socket... " >&6; }
+    (echo "use AnyEvent::Socket;" ; echo "exit(0);") | $PERL > /dev/null 2>&1
+    if test $? != 0 ; then
+	HAVE_ANYEVENT_SOCKET=no
+    else
+	HAVE_ANYEVENT_SOCKET=yes
+    fi
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $HAVE_ANYEVENT_SOCKET" >&5
+printf "%s\n" "$HAVE_ANYEVENT_SOCKET" >&6; }
+
     { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for Perl module Digest::MD5" >&5
 printf %s "checking for Perl module Digest::MD5... " >&6; }
     (echo "use Digest::MD5;" ; echo "exit(0);") | $PERL > /dev/null 2>&1
@@ -4503,6 +4558,17 @@ printf %s "checking for Perl module Net::SMTP... " >&6; }
     fi
     { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $HAVE_NET_SMTP" >&5
 printf "%s\n" "$HAVE_NET_SMTP" >&6; }
+
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for Perl module B::Keywords" >&5
+printf %s "checking for Perl module B::Keywords... " >&6; }
+    (echo "use B::Keywords;" ; echo "exit(0);") | $PERL > /dev/null 2>&1
+    if test $? != 0 ; then
+	HAVE_B_KEYWORDS=no
+    else
+	HAVE_B_KEYWORDS=yes
+    fi
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $HAVE_B_KEYWORDS" >&5
+printf "%s\n" "$HAVE_B_KEYWORDS" >&6; }
 
         dirs=`echo 'print "@INC\n";' | $PERL`
     foundit=""
@@ -8588,6 +8654,30 @@ if test "$HAVE_DKIM" = "no" ; then
    echo ""
 fi
 
+if test "$HAVE_BIMI" = "no" ; then
+   echo ""
+   echo "Could not find Mail::BIMI Perl module."
+   echo "BIMI checks will be limited to DNS record existence (no SVG/VMC validation)."
+   echo "Install it with: cpanm Mail::BIMI"
+   echo ""
+fi
+
+if test "$HAVE_CRYPT_OPENSSL_X509" = "no" ; then
+   echo ""
+   echo "Could not find Crypt::OpenSSL::X509 Perl module."
+   echo "md_verify_dane_cert() will skip TLSA records with selector=1 (SPKI)."
+   echo "Install it with: cpanm Crypt::OpenSSL::X509"
+   echo ""
+fi
+
+if test "$HAVE_ANYEVENT" = "no" || test "$HAVE_ANYEVENT_DNS" = "no" || test "$HAVE_ANYEVENT_SOCKET" = "no" ; then
+   echo ""
+   echo "Could not find all AnyEvent Perl modules (AnyEvent, AnyEvent::DNS,"
+   echo "AnyEvent::Socket).  Do not use md_async_* functions"
+   echo "in your filter.  Install them with: cpanm AnyEvent"
+   echo ""
+fi
+
 if test "$HAVE_DIGEST_MD5" = "no" ; then
    echo ""
    echo "Could not find Digest::MD5 Perl module... do not use"
@@ -8600,6 +8690,14 @@ if test "$HAVE_NET_SMTP" = "no" ; then
    echo "Could not find Net::SMTP Perl module... you will not be able"
    echo "to release quarantined messages using mimedefang-release(8)"
    echo "in smtp mode."
+   echo ""
+fi
+
+if test "$HAVE_B_KEYWORDS" = "no" ; then
+   echo ""
+   echo "Could not find B::Keywords Perl module."
+   echo "mimedefang.pl -test will skip checking filters for calls to"
+   echo "undefined subroutines."
    echo ""
 fi
 
