make IO::Socket::SSL optional, fix #48

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4062,7 +4062,7 @@ if test "$ac_cv_perlmodcheck" = "no" ; then
 $as_echo "Compile-time checking for Perl modules disabled" >&6; }
       HAVE_SPAM_ASSASSIN=yes
 else
-    for module in 'IO::Socket' 'IO::Socket::SSL' 'MIME::Tools 5.410 ()' 'MIME::WordDecoder' 'Digest::SHA1' ; do
+    for module in 'IO::Socket' 'MIME::Tools 5.410 ()' 'MIME::WordDecoder' 'Digest::SHA1' ; do
 	{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for Perl module $module" >&5
 $as_echo_n "checking for Perl module $module... " >&6; }
 	(echo "use lib '$PERLINSTALLSITELIB'; use $module;" ; echo "exit(0);") | $PERL > /dev/null 2>&1
@@ -4077,8 +4077,6 @@ $as_echo "$as_me: WARNING: *** MIME::Tools version 5.410 or higher (5.411a recom
 $as_echo "$as_me: WARNING: *** MIME::WordDecoder" >&2;}
 	    { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: *** Digest::SHA1" >&5
 $as_echo "$as_me: WARNING: *** Digest::SHA1" >&2;}
-	    { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: *** IO::Socket::SSL" >&5
-$as_echo "$as_me: WARNING: *** IO::Socket::SSL" >&2;}
 	    exit 1
 	fi
 	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: ok" >&5
@@ -4117,6 +4115,17 @@ $as_echo_n "checking for Perl module Archive::Zip... " >&6; }
     fi
     { $as_echo "$as_me:${as_lineno-$LINENO}: result: $HAVE_ARCHIVE_ZIP" >&5
 $as_echo "$HAVE_ARCHIVE_ZIP" >&6; }
+
+    { $as_echo "$as_me:${as_lineno-$LINENO}: checking for Perl module IO::Socket::SSL" >&5
+$as_echo_n "checking for Perl module IO::Socket::SSL... " >&6; }
+    (echo "use IO::Socket::SSL;" ; echo "exit(0);") | $PERL > /dev/null 2>&1
+    if test $? != 0 ; then
+	HAVE_IO_SOCKET_SSL=no
+    else
+	HAVE_IO_SOCKET_SSL=yes
+    fi
+    { $as_echo "$as_me:${as_lineno-$LINENO}: result: $HAVE_IO_SOCKET_SSL" >&5
+$as_echo "$HAVE_IO_SOCKET_SSL" >&6; }
 
         dirs=`echo 'print "@INC\n";' | $PERL`
     foundit=""
@@ -7965,13 +7974,20 @@ if test "$ac_cv_perlmodcheck" = "yes" ; then
     else
 	echo "Did not find Mail::SpamAssassin.  Do not use spam_assassin_* functions"
     fi
+    echo ""
 
     if test "$HAVE_HTML_PARSER" = "yes" ; then
 	echo "Found HTML::Parser.  You may use append_html_boilerplate()"
     else
 	echo "Did not find HTML::Parser.  Do not use append_html_boilerplate()"
     fi
-    echo ""
+fi
+
+if test "$HAVE_IO_SOCKET_SSL" = "no" ; then
+   echo ""
+   echo "Could not find IO::Socket::SSL Perl module... do not use"
+   echo "md_check_against_smtp_server function in your filter."
+   echo ""
 fi
 
 echo "Note: SpamAssassin and HTML::Parser are"
